[package]
name = "co-author"
version = "0.1.0"
edition = "2021"

[dependencies]
git = { path = "src/git" }
authors = { path = "src/authors" }
clap = { version = "4.3.19", features = ["derive"] }

[workspace]
members = [
    "src/git",
    "src/authors",
]
