[package]
name = "co-author"
version = "0.1.0"
edition = "2021"

[dependencies]
git = { path = "src/git" }
authors = { path = "src/authors" }

[workspace]
members = [
    "src/git",
    "src/authors",
]
