version: '3'
silent: true
tasks:
  default:
    cmds:
      - go-task -l
  run:
    desc: "Run in dev mode"
    cmds:
      - cargo run
  test:
    desc: "Run all tests"
    env:
      COA_ENV: test
    cmds:
      - cargo test
  test-loop:
    desc: "Loop all tests"
    env:
      COA_ENV: test
    cmds:
      - for i in {1..20}; do cargo test; done
  build:
    desc: "Build binary"
    cmds:
      - cargo build --release
