name: Build and Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update stable && rustup default stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.2.1

      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.3
        env:
          RUSTC_WRAPPER: sccache
          SCCACHE_GHA_ENABLED: true
          RUSTFLAGS: '--cfg profile=ephemeral-build'

      - name: Run build
        run: cargo build --verbose

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update stable && rustup default stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.2.1

      - name: Run clippy
        run: cargo clippy --all-targets --all-features

      - name: Run tests
        run: cargo test --verbose
        env:
          COA_ENV: test

      - name: Fake publish
        run: cargo publish --token ${CRATES_TOKEN} --dry-run --no-verify
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
